### ISSUE TITLE
다른 앱과 alarm 앱 통합을 위한 조사

### ISSUE THREAD

**Issue by lwj0712** [TangerineMarketTeam1/Gamgyul_Market#60]
alarm 앱이 다른 앱과 연동되는 구조라 아직 미완성 입니다. 일단은 제가 담당한 chat 앱과는 연동되게 만든 상태이며, 테스트 코드부터 작성했고 이를 통과한 상태입니다. 그리고 GPT에게 테스트 코드를 넘겨주고 이를 통과했다는 것에서 확인 할 수 있는 것이 무엇인지 알려 달라고 요청해봤습니다.

---
이 테스트를 통과했다는 것은 다음과 같은 의미를 가집니다:

1. 알림 생성 및 웹소켓 전송: 
   - `user1`이 `user2`에게 메시지를 보냈을 때, `user2`에게 알림이 제대로 생성되었다는 것을 의미합니다.
   - WebSocket을 통해 `user2`에게 메시지가 도착했음을 알리는 실시간 알림이 성공적으로 전송되었습니다.

2. 알림 상태 업데이트: 
   - 알림이 생성된 후, 처음에는 `is_read` 필드가 `False`로 설정되어 있음을 확인했습니다. 즉, 사용자가 알림을 아직 확인하지 않았음을 시스템이 인지하고 있었습니다.
   - 알림을 확인하고 나서 `is_read` 필드가 `True`로 전환되었습니다. 이로 인해 사용자가 알림을 확인한 상태가 제대로 기록되고 있음을 확인했습니다.

3. 웹소켓 연결 및 데이터 전송:
   - WebSocket 연결이 제대로 이루어졌고, WebSocket 통신을 통해 메시지와 관련된 알림이 실시간으로 처리되었습니다.
   - WebSocket 통신을 통한 데이터 송수신이 정상적으로 이루어졌고, 알림 메시지의 `message_id`가 정확하게 처리되었습니다.

4. 시스템 통합 성공:
   - 알림 앱과 채팅 앱, 그리고 WebSocket이 잘 통합되었음을 의미합니다. 알림 생성, 알림 읽기, 실시간 전송이 모두 의도한 대로 작동하고 있습니다.
   - 이 테스트가 성공적으로 완료됨에 따라 실시간 알림 기능이 정상적으로 작동함을 확신할 수 있습니다.

결론적으로, 이 테스트는 알림 기능이 설계대로 작동하며, 사용자가 메시지를 전송하고 상대방이 이를 실시간으로 수신 및 확인할 수 있는지 확인하는 중요한 부분을 통과했다는 것을 의미합니다. 앞으로 다른 알림 기능들(댓글, 팔로우 등)에 대해서도 유사한 방식으로 구현할 수 있습니다.

---

alarm 앱이 의도대로 작동하는 것 같습니다. 이제 다른 앱들과도 기능을 연동하면 완성될 것 같습니다.
추가적인 작업을 진행하기 위해 각 앱에서 알람 기능을 필요로 하는 부분을 댓글로 적어주시면 감사하겠습니다.

**Comment by Donggyu-Kim1** [comment]
follow 관계가 정상적으로 생성(followView)될 때 알람을 전송하는 식으로 개발해야 할 거 같습니다.

follow 모델
```
class Follow(models.Model):
    """
    팔로우 관계 모델
    """

    follower = models.ForeignKey(
        User, related_name="following", on_delete=models.CASCADE
    )
    following = models.ForeignKey(
        User, related_name="followers", on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("follower", "following")

    def __str__(self):
        return f"{self.follower.username} follows {self.following.username}"
```

**Comment by whaehofk521** [comment]
intsa 앱에서는 작성한 게시물에 댓글이 달렸을 때, 좋아요가 눌렸을 때 알림이 오게 하면 될 것 같습니다.
사용될 모델은 Post, Comment, Like 입니다.

**Comment by HwangDal85** [comment]
market app에서는 현재는 알람 기능이 필요 없을 것처럼 보입니다.
마켓에서 가장 중요한 기능인 구매는 현재 개인간 채팅 이후 거래로 정해져 있기 때문입니다.
리뷰 알림의 필요성은 잘 모르겠습니다.
