### ISSUE TITLE
논의해볼 점

### ISSUE THREAD

**Issue by Donggyu-Kim1** [TangerineMarketTeam1/Gamgyul_Market#69]
- nickname 필드가 필요한 이유 
-> username을 그대로 표시하게 되면 유저의 보안 상에 문제가 생길 우려가 존재, username은 로그인할 때 아이디에 해당하기 때문

- 이미지 썸네일이 필요한 이유? 프로필 이미지를 작게 리사이징 하기 위해
-> chat, post, market앱 프로필 사진에 이미지 썸네일(user 모델에 정의해놨습니다) 사용 가능 / 프로필 페이지에서는 크게 image로 표시
-> 이 부분은 프론트에서 작업해야 하는 지, 각 앱에서 참조해야 하는 값인지 잘 모르겠어서 질문 드립니다

- temperature 기능 
-> 현재 온도에 대한 기능이 존재하지 않습니다
-> 리뷰 결과에 의해 온도를 낮추거나 올리는 로직을 추가하는 건 어떨까요?
-> 이 부분도 논의가 필요해보입니다.

추가로 코드에 있는 기능들을 검토해주시고 추가할 부분이나 다시 작성할 부분을 정리해야 할 거 같습니다.

**Comment by lwj0712** [comment]
회원 가입 시 사용자로부터 필수로 받는 필드가
username, 이메일 주소, password, nickname이고
로그인 할 때 사용자가 입력하는 필드는 이메일 주소와 password 입니다. 
이런 구조에서 username과 nickname이 따로 존재하는 이유를 잘 모르겠습니다.
username이 nickname의 역할을, 또는 반대로 nickname이 username의 역할을 할 수 있지 않을까요?

**Comment by Donggyu-Kim1** [comment]
1. 우선 로그인 할 때 사용자가 입력하는 필드는 username과 password입니다. 
2. 그렇기 때문에 username을 페이지에서 그대로 보여주게 되면 사용자들의 아이디가 그대로 노출되게 됩니다. 그래서 보통 nickname이나 display_name 필드를 화면상에 보여주게 끔 한다고 합니다. 
3. 그래서 닉네임 필드를 회원가입 시 필수로 받게 했고 이메일 주소의 경우, 나중에 비활성화 유저가 활성화할 때 인증 구현을 위해 필수로 만들었습니다.
4. ~~결론적으로 화면 상에 보여지는 이름은 로그인을 할 때 사용할 수 있으면 안된다고 생각해서 말씀드렸습니다~~
-> 다시 생각해보니 이메일도 결국 로그인할 때 아이디가 보여지는 거나 마찬가지니 상관 없을 거 같네요
-> nickname 필드가 그럼 필요 없을 거 같아서 이 부분은 제가 수정해서 pr 올리겠습니다
6. 추가로 위도 경도 부분은 serializer에서도 삭제했습니다!

**Comment by lwj0712** [comment]
음 그렇군요 제가 잘못 알았네요. 수정하신 내용도 확인했습니다. 그럼 nickname 필드를 제거하는 방향으로 하시는 건가요? chat과 alarm앱은 test setup에서 필수 값인 nickname 을 입력하는 부분이 전부입니다.

**Comment by Donggyu-Kim1** [comment]
넵 지금 nickname을 삭제하는 걸로 작업 중에 있습니다. 그리고 추가적으로 email 필드가 필수라고 serializer에 작성되어 있는데 이메일이 없어도 회원가입이 되는거 같아서 그 부분도 수정할 거 같습니다.

그래서 일단은 test 코드에서 nickname 필드를 지워주시면 감사하겠습니다

이렇게 또 구현하려고 보니 비활성화 기능 때문에 email을 필수로 받는다는 부분이 좀 어색하네요 그래서 로그인을 아예 이메일로 받고 username을 필수로 받아 그걸로 nickname 쓰듯 하게하는건 어떤가요..

**Comment by lwj0712** [comment]
사용자 위치 관련된 기능에 대해서는 제 파트가 아니라 진행 상황에 대해 아예 잊고 있었네요. 위도 경도를 사용하는 것보단 kakaomap같은 api 사용해서 구현해보는 건 어떨까요?

**Comment by Donggyu-Kim1** [comment]
위도 경도에 대한 부분이 사실 사용자 위치 기반해서 감귤 거래를 용이하게 하거나 친구 추천을 위해 넣어 논 기능인데 이 필드도 필요 없을 거 같아서 지웠습니다.

**Comment by lwj0712** [comment]
말씀하신 대로 로그인을 이메일로 하고, username을 다른 사용자에게 보여지는 이름으로 사용하는게 관리하기도 편하고 자연스러울 것 같습니다.

**Comment by Donggyu-Kim1** [comment]
그러면 제가 내일(토요일 저녁)까지 전체적으로 수정하겠습니다. test 일단 통과되셨으니깐 기능 부분에는 영향이 없을 거 같고 내일 수정이 완료되면 그 때 테스트 코드를 수정해주시면 될 거 같네요 감사합니다

**Comment by whaehofk521** [comment]
확인이 늦었네요..! 위에서 의견나온대로 로그인을 이메일로 하는 거 좋을 것 같습니다! 이미지 썸네일의 경우 저도 잘 모르겠네요.. 프로필 페이지에서 설정한 이미지가 각 앱에서 나올 프로필 사진에서 나오는 거니까 참조를 하긴 해야할 거 같기도 하네요.. 온도는 논의가 필요해보입니다. 기능을 넣게 된다면 어느 앱에서 표기할 건지, 리뷰 결과 관련한 로직도 구체적으로 어떤 식으로 할지 등.. 나중에 얘기를 따로 해봐야할 것 같아요.

**Comment by Donggyu-Kim1** [comment]
> 말씀하신 대로 로그인을 이메일로 하고, username을 다른 사용자에게 보여지는 이름으로 사용하는게 관리하기도 편하고 자연스러울 것 같습니다.

원재님 test 코드까지 제가 수정했습니다. alarm, chat 모두 통과했습니다

**Comment by lwj0712** [comment]
앗 그럼 chat alarm앱 테스트 코드 안건드겠습니다
