### ISSUE TITLE
신고 기능에 대한 의견

### ISSUE THREAD

**Issue by lwj0712** [TangerineMarketTeam1/Gamgyul_Market#75]
신고 기능을 어떻게 구현 할 지에 대해 생각을 해봤습니다.

현재까지는 "신고 기능을 담당하는 별도의 앱을 만든다" 정도의 아이디어만 구상 된 것으로 알고 있습니다.

하지만 신고 전용 앱을 만드는 것보다 신고 기능이 필요한 앱에서 해당 기능을 추가하는 것이 더 괜찮지 않을까 생각합니다.

예를 들어, 특정 게시물에 대한 신고를 하고 싶다면

posts/<post_id>/report 와 같은 url 패턴을 생성하고, 해당 view에서는 왜 이 게시물을 신고하는 지에 대한 내용을 입력하는 필드를 만들고,  post 요청을 통해 이를 서버에 보냅니다.

그리고 이를 관리하기 위한 필드를 admin 페이지에 추가합니다.

이런 방식으로 신고기능을 구현하는게 별도의 앱을 만드는 것보다 간단하고 restful 한 구조이지 않을까 싶습니다.

어떻게 생각하시는지 의견을 적어주세요!

**Comment by Donggyu-Kim1** [comment]
좋은거 같습니다 각자 앱에서 report 기능을 알맞게 만들고 그 앱의 admin파일에 코드를 작성하는 방식인거죠? 그러면 굳이 앱을 추가하지 않아도 되겠네요

**Comment by HwangDal85** [comment]
간단히 Create view정도만 작성하면 되겠네요. 어차피 읽는건 관리자측만 읽어도 되니

**Comment by Donggyu-Kim1** [comment]
근데 신고가 관리자 단계에서 통과가 되고 부적절한 게 맞다면 그 후에 신고 당한 유저에 대한 조치는 어떻게 구현하죠?

**Comment by HwangDal85** [comment]
우리가 흔히 접했던 방식은 제재를 받은 계정으로 로그인 할 시, 계정에 대해 어떤 조치가 취해졌는지 알려준 후 로그인이 되지 않는 방식을 이용했습니다.

이를 생각해보면 계정 모델에서 정지/비정지 상태를 표시하는 속성을 추가하는 방식을 사용할 수 있겠네요. BooleanField를 이용하면 간단히 구현할 순 있겠죠.

하지만 단순히 조치를 정지/비정지 상태를 넘어서 게시물 등록 제한 등 다른 제재 기능을 넣으려면 또 백엔드 부분에서 시간을 잡아먹어서 이후 프로젝트 완성에 차질이 생길 가능성이 높아지겠네요.

**Comment by Donggyu-Kim1** [comment]
그리고 insta 앱에서 report 모델을 만들고 market에서 또 report 모델을 만드는 게 비효율적이라는 생각이 드네요.
어떻게 상각하시나요?

**Comment by lwj0712** [comment]
신고에 대한 조치는 웹사이트 운영과 정책에 대한 사항이라서 저희가 구현할 부분은 아닐 것 같다고 생각합니다.

**Comment by lwj0712** [comment]
모델까지 만들 필요는 없지 않을까요? url 만들고 view만 있으면 가능할것같습니다

**Comment by Donggyu-Kim1** [comment]
> 모델까지 만들 필요는 없지 않을까요? url 만들고 view만 있으면 가능할 것 같습니다

일단 제 생각에는 관리자가 신고 내용이 타당한 지 판단하게 하려면 관리자에게 post_id(게시글의 경우), 신고자, 신고 내용, 신고 종류 등을 받아야 한다고 생각해서 모델을 만드는 게 일반적이라고 생각했습니다. 

어차피 로직은 같을 테니  post_id(게시글의 경우) -> 이 부분을 신고 받은 필드들을 모두 받을 수 있게 구현하면 간단하게 구현할 수 있다고 생각합니다. 

혹시 이 방식으로 제가 report 앱을 구현해봐도 괜찮을까요?

**Comment by Donggyu-Kim1** [comment]
혹시 성재님께서 이미 report 기능을 개발하셨을까요?

**Comment by HwangDal85** [comment]
아직 안만들었습니다

**Comment by Donggyu-Kim1** [comment]
그냥 따로 하는 게 나을까요? 어렵네요..
